### ISSUE TITLE
Feature Request: remember how I tagged items I've bought previously

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#10]
For some reason my pet food is categorized by Amazon as "misc", but I always buy the same item and I've categorized it under Pets before. It'd be great if the tool could recognize this for any exact item I've previously tagged.

**Comment by jprouty** [comment]
This one is tricky. I'm not sure there's a straight forward way to get this working reliably. I'll think on it 👍

**Comment by noahsw** [comment]
Can you download transactions over the last X months and look for title + price matches? If a match is found, take the category that I set in Mint instead of the built-in category mapping.

**Comment by jprouty** [comment]
Okay, I have an initial implementation of this! Please give it a shot (should just work without any special cmd args).

The key details:
- Will look at all tagged Mint transactions up to 2 times older than the oldest amazon order/item you're trying to tag. (This might need some tweaking, or instead of 2x, maybe + a year back in time?). The idea here is to give enough historic mint/amazon tags to be useful to the current time period that you're tagging, without downloading ALL of your mint transactions (can be slow)
- It uses item name to do the matching, so it will not transfer the same category if you buy the same item but different style (like color, or size). Price is ignored, since those can change over time.
- It looks for the _most common_ per item name, and uses that. This means if you want to customize those paper towels you order every 4 months, you'd have to change the category on the last year or two to make sure it gets the signal.

Let me know if this is going in the right direction. I'll close the issue out for now.
