### ISSUE TITLE
Feature Request: flag to update transaction titles only

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#11]
The categorization logic needs a little bit of work for my use case (see #10 and #9) but updating the Mint titles would be killer.

Can you provide a flag that only changes Mint transaction titles?

**Comment by jprouty** [comment]
Do you find the transaction notes to be useful? Instead of only title, how about a flag for not tagging/changing category?

**Comment by jprouty** [comment]
I just committed something that ignores the category. Try `--no_tag_categories` and let me know if that works for you!

**Comment by noahsw** [comment]
So close @jprouty !

For most transactions it's not changing the category. But it still is for some:

```
$ ./tagger.py /Users/noah/Downloads/items.csv /Users/noah/Downloads/orders.csv --dry_run --no_tag_categories --mint_email

Current: 	01/07/18 	 $10.64 	 Baby Supplies 	 Amazon

Proposed: 	01/07/18 	 $10.64 	 Shopping 	 Amazon.com: Amazon Elements Baby Wipes, Sensitive, 480


Current: 	12/27/17 	 $16.99 	 Travel 	 Amazon

Proposed: 	12/27/17 	 $16.99 	 Travel 	 Amazon.com: XTRA-LARGE Fire Resistant Lipo Battery Bag for Safe Charging & Storage - 240mm x 65mm
```

**Comment by jprouty** [comment]
Okay, try again. I've moved around how the logic works... it tries for fully ignore it, which could be weird in the case of an itemized transaction... (not sure if it actually works in that case). But in the easy case of 1 existing transaction and 1 new proposed transaction it should work well 👍 

I added a `num_updates` as well that should help you test a limited number of updates when we're not sure if it'll work.

@noahsw Can you try this and report back? Specifically what happens if you try to ignore an already split/itemized transaction?

**Comment by noahsw** [comment]
Works great! Sorry for taking so long to give it a shot.
