### ISSUE TITLE
Mint Login: "I will login myself" broken in 1.59

### ISSUE THREAD

**Issue by forcey** [jprouty/mint-amazon-tagger#130]
Behavior observed: 
`Internal error while creating updates: 'NoneType' object has no attribute 'execute_script'` After Amazon reports are ready.

Expected behavior: 

Please attach your log file: /Users/forcey/MintAmazonTagger/Tagger Logs/2023-01-16_08-08-46.log
[2023-01-16_08-08-46.log](https://github.com/jprouty/mint-amazon-tagger/files/10427561/2023-01-16_08-08-46.log)

**Comment by forcey** [comment]
The same happens when I select local Amazon report and let tagger log into Mint:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/4744406/212723217-b42bd32f-e258-4554-8905-c4e90cef71e5.png">

**Comment by forcey** [comment]
Thank you for the speedy reply! Is there a way I can buy you a coffee?

**Comment by jprouty** [comment]
Sorry for the speedy reply but slower response. This should now be fixed in 1.60. Please reopen if you continue to hit this issue (or open a new issue if you run into something else). Thanks for contributing.

If you want to buy me a virtual coffee, check out my new support section in the readme. Cheers
