### ISSUE TITLE
Multiple Amazon accounts get stuck during amazon login/order history flow

### ISSUE THREAD

**Issue by dloza** [jprouty/mint-amazon-tagger#132]

**Comment by jprouty** [comment]
Hi @dloza,

I'd love to understand your use case more. Have you tried running the tagger twice (e.g. once as Amazon user A and again as user B)? I do this myself: once for my amazon account and once for my spouse's account. This ought to work fine with one Mint account (and let me know if it doesn't for some reason).

Thanks!
Jeff

**Comment by jprouty** [comment]
Thanks for the report @ashenkin. This is a regression; I'll get a fix out shortly. Cheers.

**Comment by jprouty** [comment]
Turns out the issue was with the starting URL, which recently changed in response to a new Amazon login flow. I've added the appropriate URL params back such that you are always presented with the account selector, allowing multiple amazon users to be selected (instead of attempting to use the last signed in one). Please try version 1.61 or later and reopen if the issue persists. Thanks!
