### ISSUE TITLE
Mint Transactions with 'AMAZON.COM' aren't tagged

### ISSUE THREAD

**Issue by ashenkin** [jprouty/mint-amazon-tagger#133]
Hi there,
Loving this tool.  For some reason, some of my descriptions come into mint with AMAZON.COM in all caps, and they seem to evade the tagger.  Any thoughts?
Thanks...

**Comment by jprouty** [comment]
I did find what is likely a [different issue](https://github.com/jprouty/mint-amazon-tagger/issues/134). Can you verify you are not seeing "Amazon.com:" as the description?

**Comment by ashenkin** [comment]
Here's an example of one line:
![image](https://user-images.githubusercontent.com/1608945/216434209-4b3a4c1d-fd86-4b8b-9abc-5f5efe2e5473.png)

**Comment by jprouty** [comment]
Are you able to find the "matching" amazon purchase/order? I'm curious if it's not a normal order / something else that's charged via Amazon.

**Comment by thepwnshop** [comment]
I'm having the same issue, with quite a few transactions. Attaching an example of one, but at least half are like this. Counted like 60 on the first page
<img width="692" alt="amazon order" src="https://user-images.githubusercontent.com/103589399/219897283-5673c032-c23a-46b0-8838-8960254e2061.png">
<img width="549" alt="amazon order mint" src="https://user-images.githubusercontent.com/103589399/219897304-75edc08a-340c-450a-82ae-7a1f11a1ee4c.png">

**Comment by jprouty** [comment]
Thanks @thepwnshop for sharing - this is a good start (also, I have 4x of those litter boxes - they're good for large cats!). Would it be possible to find the entry in the relevant order CSV file that matches this order number? To do this, you can click "View invoice" to find the order id. Then you'll need to find the CSV (if you're used the automated flow); the files are by default downloaded into your user/home directory, then `~/MintAmazonTagger/Amazon Order Reports/`. Please share the relevant row(s) and redact any personal information.

I'm looking for any additional information in these orders that are causing the tool to not match. Thanks

**Comment by thepwnshop** [comment]
Attached an excel that has the rows for this one in both the orders csv as well as the items csv







[Mint Amazon Tagger - Orders.xlsx](https://github.com/jprouty/mint-amazon-tagger/files/10797360/Mint.Amazon.Tagger.-.Orders.xlsx)

**Comment by jprouty** [comment]
The good news is I have enough information to verify something is amiss. I have created a new test case based on the example you've provided. https://github.com/jprouty/mint-amazon-tagger/commit/1ebeffe94ba3e9ab438f6760b9f7cb5899308670

Stay tuned, I'll need to find another time to debug what's going on.

**Comment by thepwnshop** [comment]
Thanks!

**Comment by jprouty** [comment]
I forgot how my tool works 😛 In the process of relearning the tagging rules, I figured out what you are struggling with. The tool's goal is to rename transactions like:

- `AMZN Mktp US` -> `Amazon.com: 2x of Cat Litter`
- `AMZN Mktp US***` -> `Amazon.com: Jinglong Tea Factory`

The tool then uses the special string of "Amazon.com" to detect if a mint transaction has been tagged before. When running the mint tagger, it will not consider retagging a transaction if it starts with "Amazon.com: " (unless the `retag_changed` option is selected). This allows users to change/tune/redact description contents, as well as categories without the tool messing it up on the next run.

Your transactions are coming in as "AMAZON.COM", which also match the check mentioned above, despite having never been tagged before. I have never run into this myself but based on two users reporting this now, it sounds like certain financial institutions are indeed naming it as such.

An easy fix would be to change the prefix check to also look for "Amazon.com: ", instead of "Amazon.com". I'll try this for release 1.62.

@thepwnshop Could you help me by providing the circled information from Mint for the transaction in question? I'm curious what your original transaction string looks like. Here's an example:

![Screenshot 2023-02-25 210912](https://user-images.githubusercontent.com/51562/221393498-0a1c0fae-0ab5-49ef-8558-6bc3d351e9c1.png)

**Comment by thepwnshop** [comment]
Apologies for the radio silence. 
It's coming in as: **"AMAZON.COM          AMZN.COM/BILL       WA"**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/103589399/224155572-9418364e-80c8-4322-afc8-b745f51eba8d.png">

**Comment by thepwnshop** [comment]
I've made sure I had AMAZON.COM as well as AMZN.COM and AMZN.COM/BILL and I still couldn't get it to recognize
