### ISSUE TITLE
Security question re: malware?

### ISSUE THREAD

**Issue by woodgray** [jprouty/mint-amazon-tagger#145]
Why do i keep getting this from zip Trojan.Python.Psw

**Comment by jprouty** [comment]
Hi there,

That doesn't sound right! Where/how are you downloading the tagger? The
only authentic place is from GitHub releases page, from PyPI if using
pip/command line, or cloning the repository directly.

No authentic release method deliveries the software via zip, so I'm even
more curious.

Thanks,
Jeff

**Comment by jprouty** [comment]
I found another report similar to yours from what looked like another project using pyinstaller for windows. Is it your virus scan flagging something as bad?

I ran the latest exe through virustotal and did not find any results, so that's good: https://www.virustotal.com/gui/file/663d3db51f4403939f0200b36790b8622b73548dbd3d7ebbf663bb8c1f72f5f2?nocache=1

**Comment by woodgray** [comment]
Not sure why I am using virus total. Which runs it through all the major vendor sites. It shows that two sites flagged it may be false positive who knows!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jprouty** [comment]
I'm still confused what you are reporting.

Can you clarify the source of your zip?

Can you clarify the issue you are having? (Is this your virus scanner giving a report? Or did you use an online scanner? If the latter, can you provide a link to the result?)

**Comment by woodgray** [comment]
The zip was from github your code.
The virus scanner is not a virus scanner but a report tool that takes the content and parses it through  60 different virus  scanner sites such as Norton etc .On two of the sites it failed.  Showed as trojan as described in original post.as a trojan.

**Comment by jprouty** [comment]
@woodgray Sorry for the broken record. 1) Can you give me the exact url you used? 2) Can you name/link the exact tool you used? Otherwise, I'm unable to take any meaningful action on your report.

Kindly,
Jeff

**Comment by jprouty** [comment]
I think the issue was related to: https://github.com/jprouty/mint-amazon-tagger/commit/0758d711716ce6632c95fa7946fbb807da791862

Prior to [removing the old binary](https://www.virustotal.com/gui/file/edcbc3f44303da49afa6c72ae59a38d109646dc46ebec02541e5a1935df1c312). [After](https://www.virustotal.com/gui/file-analysis/ZjEzMzdmZjkzNmIyZTgwM2Y0NGRiMzc1ZWM1ZjkwODc6MTY3NzQ1NDM0OQ==)
