### ISSUE TITLE
Tool report success when fail to submit updates with too long notes (1000+ char)

### ISSUE THREAD

**Issue by Darida** [jprouty/mint-amazon-tagger#162]
Some orders left unchanged and errors ignored when submit updates.

One case in particular - there is a 1000 char limit on notes which is exceeded when order splitted in 5-6+ items due to duplicate shipping/order dates.

I fixed the problem by modifying locally `mintamazontagger/amazon.py`

from
```
    def order_dates(self):
        return [date for items in self.items for date in items.order_date]
    
    def ship_dates(self):
        return [date for items in self.items for date in items.ship_date]
```
to
```
def order_dates(self):
    all_dates = [date for items in self.items for date in items.order_date]
    deduplicated_dates = list(set(all_dates))
    return deduplicated_dates

def ship_dates(self):
    all_dates = [date for items in self.items for date in items.ship_date]
    deduplicated_dates = list(set(all_dates))
    return deduplicated_dates
```

No errors reported, tool says 'success' but if run again, it will find these transaction again (and silencly fail to update again).

Its less than 48 hours before mint shut down so I won't be creating fork request for this. 

If you are retagging your transaction before export in the last moment like me, find the file locally and modify it.

**Comment by jprouty** [comment]
Hello @Darida. Please note that Mint has extended the sunset period as we are documenting in: https://github.com/jprouty/mint-amazon-tagger/issues/160.

This tool was recently revived to use the Amazon "Request your data" tool (instead of the prior amazon order reports tool). During that migration, I did not cleanup the notes field. Apologies about that. In release 1.66 I have added a guard to prevent 1000+ char notes, as well as a correctly formatted note with unique, formatted dates (no times) and cleaned up tracking numbers. I did not investigate why the tool is not respecting the error codes from the update failures, as the EOL nature of this tool and mint means a minimal investment on the final days. 

Consider re-running the tool with "Retag changed" in the GUI, or --retag_changed in the cli.

Thanks and Happy new year.
