### ISSUE TITLE
No items getting recategorized

### ISSUE THREAD

**Issue by dev415** [jprouty/mint-amazon-tagger#41]
I apologize if this is a silly question.  I am new to python so not super familiar with all the errors.  I successfully connected and installed the code.  When it runs in semi auto mode it sees my items but nothing gets recategorized.  If there is anything you can do to help I would appreciate it. I am sure it is something simple that I am missing. See a screenshot below.

![image](https://user-images.githubusercontent.com/53407279/62011025-cf923680-b140-11e9-8a4b-dba1d965d962.png)

**Comment by jprouty** [comment]
Hi @dev415! There's no such thing as a silly question; thanks for trying the tool out.

I have a hunch that there's something up with your refunds file. Are you sure you got the **refunds** report (instead of returns)? It may also help if you share your command line (remove all account information please).

You should be able to run just the orders + items, leaving out the refunds for the time being, and based on the error, I would guess this works correctly for you. Try that and report back.

**Comment by jprouty** [comment]
Turns out I had a bug. I'm guessing you had a recent refund that hasn't posted yet or a date is missing. Either way, I [fixed that issue here](https://github.com/jprouty/mint-amazon-tagger/commit/88e996eb305e3942a568784b26083ec3b0cc5c67).

Please update the program, and try again!
pip3 install mint-amazon-tagger --upgrade

**Comment by dev415** [comment]
Thank you!
