### ISSUE TITLE
Promotions

### ISSUE THREAD

**Issue by dev415** [jprouty/mint-amazon-tagger#42]
The tool works great! Another anomaly I just discovered is with promotions. When an item is purchased with a discount (lightning deal) the promotion comes across separate instead of part of the order.  Think there is a way to address this? See an example below.

From Mint:
![image](https://user-images.githubusercontent.com/53407279/62015915-169e1d00-b17d-11e9-8edd-e70ad07e16a6.png)

From items.csv
![image](https://user-images.githubusercontent.com/53407279/62015923-24ec3900-b17d-11e9-979f-b685af2187b4.png)

From orders.csv
![image](https://user-images.githubusercontent.com/53407279/62015987-709ee280-b17d-11e9-8f88-37267cc99810.png)

On Amazon:
![image](https://user-images.githubusercontent.com/53407279/62015937-333a5500-b17d-11e9-9cca-4a21dc50ba47.png)

Another interesting thing to note is the "Prime Savings" do not appear to be capture on any report.

**Comment by jprouty** [comment]
Hi again! Glad to hear you're having success!

This is an interesting example. Honestly, I'm not sure where the "prime savings" went, but it must be represented in the report somehow, as the tagged "promotions" are showing 77.61 (74.61 + 3).

It's true, the type of promotion (and number of promotions) are not represented in the reports (thanks amazon!), so that's the level of granularity.

There's two flags that you can play with. The default behavior:
  --verbose_itemize     Default behavior is to not itemize out
                        shipping/promos/etc if there is only one item per Mint
                        transaction. Will also remove free shipping. Set this
                        to itemize everything.
  --no_itemize          Do not split Mint transactions into individual items
                        with attempted categorization.

If the order you referenced in this issue only has 1 item, and you didn't specify --verbose_itemize, then I'm not really sure why you're seeing the mint transaction being itemized as you are (split into different line items). If you'd like to always condense into a single line item per order, then take a look at --no_itemize, which will always merge in Promotions into the line item itself.

**Comment by dev415** [comment]
Thanks for the quick response.  I looked at two examples and they both have multiple items in the order.  I do not have --verbose_itemize specified.  My preference would be to have the promotions grouped with the item even on multi item orders. It appears that you can isolate and identify by looking at orders.csv.  Let me know your thoughts.

**Comment by dev415** [comment]
Just checking to see if you had any thoughts on this?

**Comment by jprouty** [comment]
To clarify, the promotions are totaled/associated at the order/charge level. Amazon doesn't split it out any further. So for example, an order with 5 items, one that has 15% off, and the whole order has free same day shipping (shown sometimes as a promo), and you have a primeday discount, all of those would get bunched up into one promotion on the whole order/shipment.

If you don't like the style where the mint transaction splits out the charge into each item, you can do --no_itemize, which will then merge all the items, shipping, and promos all into one mint line item.

Let me know if I'm misunderstanding. If you anonymize a specific example, I'm happy to take a closer look!

**Comment by jprouty** [comment]
@dev415, let me know if my previous reply made sense and if you have any specific examples you can share from your reports (if my response didn't make sense).

**Comment by jprouty** [comment]
@dev415 I haven't heard back from you; I'm going to close this because as far as I can tell, what you're asking is infeasible due to the way Amazon models their data in the export. Please reopen and reply to my above messages if you'd like to dig deeper!
