### ISSUE TITLE
Few transactions matched

### ISSUE THREAD

**Issue by glassdimly** [jprouty/mint-amazon-tagger#50]
I found that of my ~86 Amazon transactions, only ~5 were being matched.

Pull request [49](https://github.com/jprouty/mint-amazon-tagger/pull/49) got me to only 25/86 unmatched.

**Comment by glassdimly** [comment]
Also, I created https://github.com/jprouty/mint-amazon-tagger/pull/53/files to address this.

**Comment by jprouty** [comment]
Hi @glassdimly! Thanks for filing the various issues and sending in PRs! I hope this tool is useful for you (once we get it working better for you ;-) )

PR 49 specifically isn't quite what I want to commit. The reason has to do with how mint uses the various "merchant" fields. Of course, this api isn't documented, but based on other API users and personal experience working with the mint product for a decade, I believe this is an accurate description of the fields, and ordered based on the life of a transaction:

1. Amazon attempts to pay for your order, and they can and may choose a different payment description to use when running a payment with the payment processor.
2. Amazon also has their own [payment processor ](https://en.wikipedia.org/wiki/Payment_processor) inhouse (some pieces are exposed in the external "Amazon payments" product). The payment processor layer can keep the description or choose to obfuscate it when dealing with your institution.
3. Money is deposited/credited from your institution. At this point, your institution could decide to make this more "useful" for you, simply summarizing it as "Debit card purchase 4321". Note, there are/can be additional fields/info related to this transaction.
4. Mint imports the data. **omerchant**: This is the exact text for the transaction from your institution.
5. Mint tries to rename transactions into something useful again, that's actually related to what was purchased. There are a few phases to this step: (a) _not configurable by the user_, mint tries to rename based on other information about the transaction (see step 3 above). This information is _not_ exposed in the product (b) _not configurable by the user_, Mint tries to learn user specific renaming, and will auto apply changes for you (c) _user configurable_, the user can specify simple rename rules: when you see "AMZN" always rename to "I love spelling, it's spelled Amazon not AMZN". The result of these renames ends in **mmerchant**
6. From the product webpage, if the user renames the transaction at any point, the **merchant** field is updated.
7. Finally, regardless of what phases above were triggered for a given transaction, the description shown in the Mint product is the **merchant** field. If a phase was skipped, then omerchant -> mmerchant -> merchant are just copied verbatim.

Here's a real example from my Mint history:
```
merchant: Amazon.com: OXO Good Grips Easy to Clean Pizza Wheel and Cutter
mmerchant: Skoy Eco-friendly Cleaning Cloth (4-pack: Assorted Colors)
omerchant: Amazon.com
```

^ For me, Mint has learned (against my will) that every "Amazon.com" transaction should instead be renamed to "Skoy ...". This is absolutely not what I want. This tool was run against this transaction, and ended up renaming it to "Amazon.com; OXO Good Grips ..."

Back to your issue, it seems that your bank is naming your transactions poorly, "Debit card Purchase", but Mint is actually somewhat help, and is renaming them "Amazon". In your case, it seems helpful that looking at mmerchant (in addition to omerchant) when determining if each transaction is an amazon purchase. However, I would suggest avoiding merchant, as this could accidentally include non-amazon purchases, including both auto-renamed and user renamed transactions. Similarly, using mmerchant isn't ideal, as it will pick up non-amazon purchases. For example, say you have an amazon credit card, and you have a rule or mint learned that you want these called "Transfer to Amazon Visa". These would unintentionally be considered for matching (and could actually be falsely matched against a purchase). There can be two sides to this transfer, a credit to the credit card account, and a debit from the bank account (so this becomes a problem for matching both purchases and refunds).

Real example from my mint:
```
merchant: Transfer to Amazon Visa
mmerchant: Transfer to Amazon Visa
omerchant: CHASE CARD SERV ONLINE PMT
```

So, to make this tool useful to you, I'll add two new arguments that default to off (as I believe the current behavior is more conservative; and ruining someone's mint account is the last thing I want to do):
--mint_input_include_mmerchant
--mint_input_include_merchant

I'll update the main readme to include some debugging tips and things to try when you're having a low match rate. I'll also add some notes that this tool by nature may require some tuning based on your situation/banks/etc (which is why there are so many flags) :)

I hope that helps! Thanks for bringing this up, as I only have a limited view of what various mint/amazon data can look like.

**Comment by jprouty** [comment]
Marking this as closed; I'll release a new version shortly with those improvements.

**Comment by glassdimly** [comment]
Great points, thanks for considering this PR and for adding these changes. I want to help match as many transactions as possible and make this module valuable to folks.

I had a question about your example:

>  For example, say you have an amazon credit card, and you have a rule or mint learned that you want these called "Transfer to Amazon Visa". These would unintentionally be considered for matching (and could actually be falsely matched against a purchase). 

It would be my understanding that if this transaction were to be matched by this tagger, it would need to have been created 3 days from an Amazon transaction ship date whose total amount precisely matched the credit card amount, which seems like an edge case. Or am I mistaken?

**Comment by jprouty** [comment]
You are correct; depending on the volume of your orders (and also how often you might choose to pay off the credit card) would increase your chances for a "conflict" within that time frame, and ultimately tagging the inappropriate transaction, also potentially on an inappropriate account in mint (the account that payed off the card).

Similarly, by increasing the days from 3 -> 7, if you happen to have bought a bunch of the same item, but they shipped in different orders, and spawned out a bunch of same payments in a few day cluster, this can cause a problem (true story). Again, should totally be fine, but all depends on how you use amazon, and in your case, how quick your bank/CC is at posting payments.

**Comment by glassdimly** [comment]
Roger. Yeah, for my purposes, and probably for most users, a few false labels is not as bad as tons of unmatched transactions.

Regardless, you kinda have to look over everything by hand in the end anyway.

**Comment by jprouty** [comment]
Mint has recently changed its API models. I believe the mapping from old to new is now:

| Old API     | New API    | Description             |
| ----------- | ----------- | ---------------------- |
| `transaction.omerchant` | `transaction.fiData.description` | The original description provided by the financial institution. |
| `transaction.mmerchant`  | `transaction.fiData.inferredDescription`| The description that Mint infers based on additional context or user-defined rules. By default it will be the same as `fiData.description`. |
| `transaction.merchant` | `transaction.description` | The "live description" in Mint. It may be set by the user or by default it will be the same as `fiData.inferredDescription` (and likely also `fiData.description`). |
