### ISSUE TITLE
Groceries marked as personal care

### ISSUE THREAD

**Issue by nchernia** [jprouty/mint-amazon-tagger#69]
Great tool, thanks!

My groceries (a lot of Amazon Fresh these days) are all being marked Personal Care. Including really obvious things like apples. 

I looked a little at category.py and saw that you had a note about it. Do you have suggestions for modifying category.py? Right now I'm stuck manually reclassifying ~1000 items and I don't want to do that.

**Comment by jprouty** [comment]
Hi @nchernia, glad your finding this tool to be useful!

The good news is that this should be pretty easy to fix! I don't use Amazon fresh, so I don't really have any good sample data to reference when I was revamping the categories. If possible, would you be able to send me (jeff.prouty@gmail.com) an anonymized version of your items amazon report? Feel free to delete all your personal details from the relevant columns. You can also delete any rows that are private. I really only need the UNSPSC and description columns.

 Thanks!

**Comment by jprouty** [comment]
Okay, release 1.33 should do the trick! I'm not sure how you were using the tool, but if it's a prebuilt version, take a look at the [releases page](https://github.com/jprouty/mint-amazon-tagger/releases). I would recommend reusing the same orders/items files you've already downloaded, but then selecting the _retag_ option, which should try to recategorize these for you (otherwise, the tool will try to skip things it thinks it has already tagged).

**Comment by nchernia** [comment]
The pre built binary (dmg) is not working - opens then immediately closes. I'm going to try from source.

**Comment by nchernia** [comment]
OK going through pip didn't work either. Even just running help returns an error.

mint-amazon-tagger --help
Traceback (most recent call last):
  File "/Users/nchernia/anaconda3/bin/mint-amazon-tagger", line 6, in <module>
    from mintamazontagger.main import main
  File "/Users/nchernia/anaconda3/lib/python3.6/site-packages/mintamazontagger/main.py", line 30, in <module>
    from mintamazontagger import tagger
  File "/Users/nchernia/anaconda3/lib/python3.6/site-packages/mintamazontagger/tagger.py", line 36, in <module>
    None, None, None, None, None, None))
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

**Comment by jprouty** [comment]
Well that is certainly not helpful :-P Thanks for the report!

I probably won't have a chance to look into this until this evening, but it appears to all be self contained within the tool.

**Comment by nchernia** [comment]
Might be Python 3.6 vs 3.7

**Comment by nchernia** [comment]
That seems to be the problem, I changed the Python 3.7 after some amount of work and it's fine. Found it referenced in another repo. https://github.com/yzhangcs/parser/issues/15

**Comment by jprouty** [comment]
@nchernia , you're right on the money re: Python 3.7. However, I'm still surprised the dmg didn't work for you. It should contain its own python version, which should prevent these sorts of issues or for people who think python is a snake.

Would you mind reporting back if the dmg version works now that you also updated to 3.7?

**Comment by nchernia** [comment]
The DMG still doesn't work, it fails to open. I changed my Python environment using pyenv; would make sense that Python should be included in DMG.

Some other notes:
- the CLI Mint tagger says it will prompt for Mint email and password if not given, but does not; I'd rather be prompted for a password, especially
- I'm still having trouble with the retag and I wonder if it's because the software thinks that I put those categories in? Things like apples and Pepperidge Farm goldfish crackers are still listed as Personal Care.

"Transactions with personalize categories: 1309" <--- I think it's not retagging these?

**Comment by jprouty** [comment]
Thanks for all the detailed info! This is all very useful. What version mac OS are you running? I'm on big sur and concerned I won't be of much help trying to get the dmg to work.

I'll look closer at the CLI issue in a bit.

Good catch on the personalized categories! I'm impressed you noticed that. Please try:
- GUI: check booth the "retag" checkbox and the "Do not predict categories" checkbox
- CLI: add both `--retag_changed --do_not_predict_categories`

Since I changed the "system default" categories for the tool, it's noticed that your mint data doesn't match what the tool now thinks they should be by default, and therefore thinks you personally chose those categories. As such, it's trying to predict what you'd want instead based on your past behavior. In this case it's a bit odd, as it's not really your behavior. Anyway, those flags should actual nuke it by disabling the category prediction logic.
