### ISSUE TITLE
Error in console window

### ISSUE THREAD

**Issue by DavidLangworthy** [jprouty/mint-amazon-tagger#75]
I'm really excited to try this out, but I'm running into some problems.  One thing I've figured out is not to click Sign In as soon as the captive browser opens up.  The automation wants to do that.  After I'm in the password does not populate automatically.  Should I just wait?  I've tried logging in with a text but that does not seem to help.  Also, I'm getting this error in the console window.  Is it benign?  

```
  [8500:4956:0607/203700.828:ERROR:device_event_log_impl.cc(214)] [20:37:00.827] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
```

I am running on windows.

**Comment by DavidLangworthy** [comment]
I figured out one more issue.  If the password that is given is incorrect, the automation pastes it again and again and triggers the auto lockout mode.

Would it be possible to have a mode where the automation did not try to log in.  Just let the user login, then take it from there?

One thing that might be throwing it off is that I have multiple mint accounts so go to an account discovery page first.

**Comment by jprouty** [comment]
Hi @DavidLangworthy, sorry for all the trouble! Yes, if you manually log in sometimes it will work. This depends on the phase of the mintapi login flow. This project doesn't implement the mint interaction/interface ([see mintapi](https://github.com/mrooney/mintapi) for background).

I've never seen the repeated password login behavior you describe. It could be new; maybe worth filing over at the mintapi team.

I also do not believe there is a mode that allows for you to login yourself instead of the automation. However, this seems like a compelling feature/idea and worth introducing.

I'm curious what version you're on. There were some recent changes to mintapi that should have helped support this multi-account scenario. I took these changes when making the latest release of this project; if you're using a downloaded binary, maybe double check you have the latest? Or if pip, do a `pip3 install --upgrade mint-amazon-tagger`

**Comment by DavidLangworthy** [comment]
This is super helpful, thank you.  I'll do 3 things:
1. Update chrome to latest
3. Clear my mint cookies so it doesn't look like I have multiple accounts
2. Get Mint API to work from command line
I'm on a fresh download of tagger so I assume a fresh version of mint-api.

I'll let you know what I find.  Thanks again.

**Comment by jprouty** [comment]
Closing until you reproduce. Thanks
